import { CONTENT_TYPE, AUTHORIZATION_BEARER } from './common';

export const DISJOIN_EVENT_HEADERS = {
  CONTENT_TYPE,
  AUTHORIZATION_BEARER,
};

export const FORGOT_PASSWORD_HEADER = {
  ...CONTENT_TYPE,
};

export const GET_MY_EVENT_HEADERS = {
  CONTENT_TYPE,
  AUTHORIZATION_BEARER,
};

export const JOIN_EVENT_HEADERS = {
  CONTENT_TYPE,
  AUTHORIZATION_BEARER,
};

export const LOGIN_HEADERS = {
  ...CONTENT_TYPE,
};

export const REFRESH_TOKEN_HEADERS = {
  ...CONTENT_TYPE,
};

export const REGISTER_HEADER = {
  ...CONTENT_TYPE,
};

export const ACTIVATE_ACCOUNT_HEADERS = {
  ...CONTENT_TYPE,
};

export const SEND_EMAIL_VERIFICATION_HEADER = {
  ...CONTENT_TYPE,
};
