import { CONTENT_TYPE, AUTHORIZATION_BEARER } from './common';

export const GET_EVENTS_HEADERS = {
  ...CONTENT_TYPE,
};

export const CREATE_EVENT_HEADERS = {
  ...CONTENT_TYPE,
};

export const DELETE_EVENT_HEADERS = {
  CONTENT_TYPE,
  AUTHORIZATION_BEARER,
};
