import {
  CONTENT_TYPE,
  AUTHORIZATION_BEARER,
  AUTHORIZATION_BEARER_OPTIONAL,
} from './common';

export const CREATE_POLL_HEADERS = {
  CONTENT_TYPE,
  AUTHORIZATION_BEARER,
};

export const GET_POLLS_HEADERS = {
  CONTENT_TYPE,
  AUTHORIZATION_BEARER_OPTIONAL,
};

export const VOTE_POLL_HEADERS = {
  CONTENT_TYPE,
  AUTHORIZATION_BEARER,
};
