import { CONTENT_TYPE, AUTHORIZATION_BEARER } from './common';

export const CREATE_POLL_HEADERS = {
  CONTENT_TYPE,
  AUTHORIZATION_BEARER,
};

export const GET_POLLS_HEADERS = {
  CONTENT_TYPE,
  AUTHORIZATION_BEARER,
};
