services:
  mongodb:
    container_name: mongodb
    networks: 
      - esmorga-net
    image: mongodb/mongodb-community-server:latest
    volumes:
      - ./.docker_mongo:/data/db
    ports:
      - 27017:27017
  esmorga:
    container_name: esmorga
    networks: 
      - esmorga-net
    build:
        context: ./
    environment:
      - MIGRATION_ENV=COMPOSE
      - MONGODB_URI=mongodb://mongodb:27017/esmorga
      - APP_PORT=3000
      - DNS_NAME=http://localhost:3000/
      - AIO_TOKEN=MDZhOTk5YjItYjE4MC0zMWFlLTllMDMtZDE2ZTRhNTAzYjczLjY5NzA3ZmQ3LTU0Y2UtNDk5NS04OTc4LWNhMGM2MTkyMjdmZQ==
      - JWT_SECRET=edF06oXM88eLJjdMgtgGVHCreGT8vGgzTMKRrIxwZu0=
      - JWT_REFRESH_SECRET=uipdpBXtPEpJSvzce/3vt+WE+IshNiovCzhKk44s1UE=0
      - ACCESS_TOKEN_TTL=600
      - MAX_PAIR_OF_TOKEN=5
      - APP_LINK=https://www.google.com
      - EMAIL_USER=esmorgamailservice@gmail.com
      - EMAIL_PASS=piop hszr qkww uexk
      - LOGIN_ATTEMPTS_TTL=60
      - MAX_LOGIN_ATTEMPTS=5
    ports:
      - 3000:3000
networks:
  esmorga-net: