name: "Prepare Env"
description: "Prepare Env"
runs:
  using: "composite"
  steps:
      - name: Set up Python "pypy3.9"
        uses: actions/setup-python@v5
        with:
          python-version: "pypy3.9"
      - name: Install dependencies And Deploy to QA
        shell: bash
        run: |
          python .github/workflows/scripts/createENV.py