name: "Run Postman Tests"
description: "Run Postman Tests"
inputs:
  SLACK_WEBHOOK_URL:
    description: 'URL'
    required: true
  POSTMAN_TOKEN:
    description: 'TOKEN'
    required: true
  DESPOSABLE_EMAIL_USER:
    description: 'DESPOSABLE EMAIL USER'
    required: true
  DESPOSABLE_EMAIL_PASS:
    description: 'DESPOSABLE EMAIL PASS'
    required: true

runs:
  using: "composite"
  steps:
        - name: Install dependencies & Run Postman Test
          shell: bash
          id: test-postman
          run: |
            curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
            postman login --with-api-key ${{inputs.POSTMAN_TOKEN}}
            postman collection run 25091136-0af5bd1f-1b37-450c-b138-b961128c40ec -e 34733067-4a57f5f3-ba99-4cdb-95a2-d89e4aaa24b7 --global-var mail_auth_user=${DESPOSABLE_EMAIL_USER} --global-var mail_auth_password=${DESPOSABLE_EMAIL_PASS}
            postman collection run 34733067-87db0ada-5ec1-435a-a33d-4cd36d19656d -e 34733067-dad4bba4-8253-4270-bb57-87cfe224d433

        - name: Run Reporting
          uses: ./.github/actions/SlackCom
          with: 
            msg: "Backend Postman Test Fails"
            SLACK_WEBHOOK_URL: ${{ inputs.SLACK_WEBHOOK_URL }}
          if: failure()
