name: "Run Postman Tests"
description: "Run Postman Tests"


runs:
  using: "composite"
  steps:
        - name: Install dependencies & Run Postman Test
          shell: bash
          id: test-postman
          run: |
            curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
            postman login --with-api-key ${POSTMAN_TOKEN}
#            postman collection run "test/postman/(Generator) Contract Tests - OAS3.postman_collection.json" -e "test/postman/Contract Test local on Pipeline.postman_environment.json"
#            postman collection run "${{ github.workspace }}/TESTS.json" -e "34733067-4a57f5f3-ba99-4cdb-95a2-d89e4aaa24b7"
          # Lint your API using Postman CLI
#            postman api lint d7b833e3-1440-455b-88d7-e259351c4cb5
          # Run Api contract
#            postman collection run 34733067-87db0ada-5ec1-435a-a33d-4cd36d19656d -e 34733067-dad4bba4-8253-4270-bb57-87cfe224d433 --env-var env-apiKey = ${POSTMAN_TOKEN}
          # Run Colection 
#            postman collection run 25091136-0af5bd1f-1b37-450c-b138-b961128c40ec -e 34733067-4a57f5f3-ba99-4cdb-95a2-d89e4aaa24b7
        - name: Run Reporting
          uses: ./.github/actions/SlackCom
          with: 
            msg: "Postman Test Fails"
            SLACK_WEBHOOK_URL: ${{ inputs.SLACK_WEBHOOK_URL }}
#          if: failure()
          if: always()