name: "Run E2E Tests"
description: "Run E2E Tests"
runs:
  using: "composite"
  steps:
        - name: Install dependencies & Run Postman Test
          shell: bash
          id: test-postman
          run: |
            curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
            postman login --with-api-key ${{ secrets.postmanToken }}
            postman collection run 25091136-0af5bd1f-1b37-450c-b138-b961128c40ec -e 25091136-b857199d-2fd0-43c3-a231-24249d76d33f
       
