name: "Run Service"
description: "Run Service"
runs:
  using: "composite"
  steps:
        - name: Install dependencies
          env:
            API_RATE_LIMIT: 100
            API_RATE_LIMIT_TTL: 60
            PUBLIC_API_RATE_LIMIT: 100
            PUBLIC_API_RATE_LIMIT_TTL: 100

          shell: bash
          run: |
            npm ci
            npx mongo-migrate-ts up
            npm run start &
            sleep 10
