name: "Deploy"
description: "Deploy"
inputs:
  SSHRSA:
    description: 'SSH RSA'
    required: true

runs:
  using: "composite"
  steps:
      - name: Set up Python "pypy3.9"
        uses: actions/setup-python@v5
        with:
          python-version: "pypy3.9"
      - name: Install dependencies And Deploy
        shell: bash
        run: |
          python -m pip install --upgrade pip paramiko 
          python .github/workflows/scripts/DeployToEnv.py esmorga.canarte.org ${{inputs.SSHRSA}}