# I need this code for next Task
name: "MSG to Slack"
description: "MSG to Slack"
inputs:
  msg:
    description: 'What to send'
    required: true
    default: 'Is this an error?'
  SLACK_WEBHOOK_URL:
    description: 'URL'
    required: true


runs:
  using: "composite"
  steps:
      - name: Send custom JSON data to Slack workflow
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "text": "${{ inputs.msg }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ inputs.SLACK_WEBHOOK_URL }}
