name: "Push OAS to github"
description: "Push OAS to github"
inputs:
  PAT:
    description: 'A Github key'
    required: true
runs:
  using: "composite"
  steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}



      - name: Push OAS to github
        shell: bash
        run: |
          echo ${GITHUB_HEAD_REF} > /tmp/branch.txt
          curl http://127.0.0.1:3000/swagger-json -o /tmp/swagger.json
      - name: Push OAS to github
        shell: bash
        run: |
          if ! cmp -s "/tmp/swagger.json" "swagger.json"; then
          cp /tmp/swagger.json swagger.json
          exit 1
          fi
      - name: Push OAS to github
        shell: bash
        run: |
          if ! cmp -s "/tmp/branch.txt" ".github/tmp/branch.txt" ; then
          cp /tmp/branch.txt .github/tmp/branch.txt
          exit 1
          fi

      - name: Update Git
        if: failure()
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
          git fetch --unshallow
          git checkout ${{ github.head_ref }}
          git pull
          git merge --no-ff ${{ github.ref }} -m "Auto-merge ${{ github.ref }} to  ${{ github.head_ref }}"
          git push