name: "Push OAS to github"
description: "Push OAS to github"
runs:
  using: "composite"
  steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 

      - name: Push OAS to github
        shell: bash
        run: |
          Push=0
          echo ${GITHUB_HEAD_REF} > /tmp/branch.txt
          curl http://127.0.0.1:3000/swagger-json -o /tmp/swagger.json
          if ! cmp -s "/tmp/swagger.json" "swagger.json"; then
          cp /tmp/swagger.json swagger.json
          git add swagger.json
          Push=1
          fi
          if ! cmp -s "tmp/branch.txt" ".github/tmp/branch.txt" ; then
          cp /tmp/branch.txt .github/tmp/branch.txt
          git add .github/tmp/branch.txt
          Push = 1
          fi

          if [ $Push -ne 0 ] ; then
          git config --global user.email "devops@esmorga.canarte.org"
          git config --global user.name "Pipe"
          git commit -m "ADD Files"
          git push origin HEAD:refs/heads/${GITHUB_HEAD_REF}
          fi
