name: "Deploy to QA"
description: "Deploy to QA"
runs:
  using: "composite"
  steps:
      - name: Set up Python "pypy3.9"
        uses: actions/setup-python@v5
        with:
          python-version: "pypy3.9"
      - name: Install dependencies And Deploy to QA
        shell: bash
        run: |
          python -m pip install --upgrade pip paramiko 
          python .github/workflows/scripts/DeployToEnv.py qa.esmorga.canarte.org ${SSHRSA}