name: "Run Unit Tests"
description: "Run Unit Tests"
runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.1'
        
    - name: Install dependencies
      run: npm ci
      shell: bash

    - name: Run tests now
      run: npm run test:cov:unit
      shell: bash
