name: "Run E2E Tests"
description: "Run E2E Tests"
runs:
  using: "composite"
  steps:
        - name: Install dependencies & Run
          shell: bash
          run: |
           echo ${CYPRESS_BASE_URL}
           npm ci
           sleep 60
           npm run test:e2e-run-cypress
