name: "Run E2E Tests"
description: "Run E2E Tests"
runs:
  using: "composite"
  steps:
        - name: Install dependencies
          run: npm ci
          shell: bash
        - name: Start service
          run: npm run start
          shell: bash
        - name: Run tests now
          run: npm run test:e2e-run-cypress
          shell: bash
        - name: Stop service
          run: npm run stop
          shell: bash