name: "Run E2E Tests"
description: "Run E2E Tests"
runs:
  using: "composite"
  steps:
        - name: Set TERM environment variable
          shell: bash
          run: echo "TERM=xterm-256color" >> $GITHUB_ENV
        - name: Install dependencies & Run
          shell: bash
          run: |
           npm ci
           npm run test:e2e-run-cypress
        - name : Upload Results
          shell: bash
          if: always()
          run: node test/scripts/features-tool.js report/junit-e2e.xml --Upload-Results 
