name: "Run E2E Tests"
description: "Run E2E Tests"
inputs:
  SLACK_WEBHOOK_URL:
    description: 'URL'
    required: true
runs:
  using: "composite"
  steps:
        - name: Set TERM environment variable
          shell: bash
          run: echo "TERM=xterm-256color" >> $GITHUB_ENV
        - name: Install dependencies & Run
          shell: bash
          run: |
           npm ci
           npm run test:e2e-run-cypress
        - name: Run Reporting
          uses: ./.github/actions/SlackCom
          with: 
            msg: "Backend  E2E Test Fails"
            SLACK_WEBHOOK_URL: ${{ inputs.SLACK_WEBHOOK_URL }}
          if: failure()
        - name : Upload Results
          shell: bash
          if: always()
          run: node test/scripts/features-tool.js report/junit-e2e.xml --Upload-Results 
