name: "Run E2E Tests"
description: "Run E2E Tests"
inputs:
  SLACK_WEBHOOK_URL:
    description: 'URL'
    required: true
  MOCK_SERVER_USERNAME:
    description: 'Username for Mock Server'
    required: true  
  MOCK_SERVER_PASSWORD:
    description: 'Password for Mock Server'
    required: true
runs:
  using: "composite"
  steps:
        - name: Set TERM environment variable
          shell: bash
          run: echo "TERM=xterm-256color" >> $GITHUB_ENV
        - name: Install dependencies & Run
          shell: bash
          run: |
           npm ci
           echo "MOCK_SERVER_USERNAME=${{ inputs.MOCK_SERVER_USERNAME }}" > test/cypress-e2e/.env
           echo "MOCK_SERVER_PASSWORD=${{ inputs.MOCK_SERVER_PASSWORD }}" >> test/cypress-e2e/.env
           npm run test:e2e-run-cypress
        - name : Upload Results
          shell: bash
          if: always()
          run: |
                if [ "${GITHUB_HEAD_REF}" == "" ]; then
                node test/scripts/features-tool.js report/junit-e2e.xml --Upload-Results 
                fi
        - name: remove env file
          shell: bash
          run: |
            rm test/cypress-e2e/.env
