name: "Run Component Tests"
description: "Run Component Tests"
inputs:
  GITHUB_TOKEN:
    description: 'A Github PAT'
    required: true
runs:
  using: "composite"
  steps:
        - name: Install dependencies
          run: npm ci
          shell: bash
        - name: Merge Covergage
          run: npm run test:merge-coverage 
          shell: bash
        - name: Create Report
          run: npm run test:report
          shell: bash
        - name: Coverage report on Git Hub
          uses: boris-amenitiz/lcov-pull-request-report@v1.0.0
          with:
           lcov-file: coverage/lcov.info
           github-token: ${{ inputs.GITHUB_TOKEN }}
           comment-title:
           all-files-minimum-coverage: 0
           changed-files-minimum-coverage: 0


      #   if: failure() && steps.unit-tests.outcome == 'failure'
      #   run: node test/scripts/features-tool.js report/junit-unit.xml --Upload-Results 
      # - name : Run Component Tests
      #   id: component-tests
      #   run: npm run test:cov:component
      # - name : Upload Results
      #   if: failure() && steps.component-tests.outcome == 'failure'
      #   run: node test/scripts/features-tool.js report/junit-component.xml --Upload-Results


