name: "Run Component Tests"
description: "Run Component Tests"
runs:
  using: "composite"
  steps:

        - name: Install dependencies
          run: npm ci
          shell: bash
        - name: Merge Covergage
          run: npm run test:merge-coverage 
          shell: bash
        - name: Create Report
          run: npm run test:report
          shell: bash