name: "Merge Coverage files"
description: "Merge Unit and Component coverage files and create a report on GitHub"
inputs:
  GITHUB_TOKEN:
    description: 'A Github PAT'
    required: true
runs:
  using: "composite"
  steps:
        - name: Merge Covergage
          run: npm run test:merge-coverage 
          shell: bash

        - name: Create Report
          run: npm run test:report
          shell: bash

        - name: Coverage report on Git Hub
          uses: boris-amenitiz/lcov-pull-request-report@v1.0.0
          with:
           lcov-file: coverage/lcov.info
           github-token: ${{ inputs.GITHUB_TOKEN }}
           comment-title:
           all-files-minimum-coverage: 0
           changed-files-minimum-coverage: 50



