name: Run Tests & Deploy QA ENv
run-name: ${{ github.actor }} is testing to deploy new code to QA Env 🚀
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches:
      - main
  workflow_dispatch:
    
    
jobs:
  Run-tests-on-Ubuntu:
    name: Run npm test on Ubuntu
    runs-on: ubuntu-latest
    env:
      APP_PORT: 3000
      MONGODB_URI: "mongodb+srv://NewServerQA:ohdDcwCDce1uzq5n@clousterqa.xofidzb.mongodb.net/esmorga?retryWrites=true&w=majority&appName=ClousterQA"
      REDIS_HOST: "redis-10358.c6.eu-west-1-1.ec2.redns.redis-cloud.com"
      REDIS_PORT: 10358
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.1'
      - run: echo $APP_PORT
      - run: npm ci
      - run: npm run test:integration
        if: ${{ success() }}
      
  deploy:
        needs: Run-tests-on-Ubuntu
        runs-on: ubuntu-latest
        steps:
          - name: Request approval
            uses: actions/github-script@v4
            with:
              github-token: ${{ secrets.GITHUB_TOKEN }}
              script: |
                const { owner, repo, number } = context.issue;
                await github.pulls.createReviewRequest({
                  owner,
                  repo,
                  pull_number: number,
                });