name: Run Tests & Deploy QA ENv
run-name: ${{ github.actor }} is testing to deploy new code to QA Env 🚀
on:
  pull_request:
    types: [closed]
    branches:
      - main
  workflow_dispatch:
  
jobs:
  Run-tests-on-Ubuntu:
    name: Run npm test on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.1'
      - run: npm install
      - run: npm run test:integration
