name: Create Release
run-name: ${{ github.actor }} is creating a release 🚀
on:
  workflow_dispatch:
    inputs:
      release_num:
        description: release number
        required: true
      usKey:
        description: release number
        required: true


jobs:
  CreateRelease:
    name: Create release github.event.client_payload.branch
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4


    - name: Create .env
      run: |
        echo APP_PORT=${{vars.APP_PORT}} >> .env 
        echo MONGODB_URI=${{secrets.MONGODB_URI}} >> .env 
        echo NODE_ENV=${{vars.NODE_ENV}} >> .env 
        echo JWT_SECRET=${{secrets.JWT_SECRET}} >> .env 
        echo ACCESS_TOKEN_TTL=${{vars.ACCESS_TOKEN_TTL}} >> .env 
        echo MAX_PAIR_OF_TOKEN=${{vars.MAX_PAIR_OF_TOKEN}} >> .env 
        echo EMAIL_USER=${{vars.EMAIL_USER}} >> .env 
        echo EMAIL_PASS=${{secrets.EMAIL_PASS}} >> .env 
        echo APP_LINK=${{vars.APP_LINK}} >> .env 
        echo LOGIN_ATTEMPTS_TTL=${{vars.LOGIN_ATTEMPTS_TTL}} >> .env 
        echo MAX_LOGIN_ATTEMPTS=${{vars.MAX_LOGIN_ATTEMPTS}} >> .env 
