name: Create Release
run-name: ${{ github.actor }} is creating a release 🚀
on:
  workflow_dispatch:
    inputs:
      release_num:
        description: release number
        required: true
      usKey:
        description: US key to link to this new branch
        required: true


jobs:
  CreateRelease:
    name: Create release github.event.client_payload.branch
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.G_PAT }}


    - name: Create Release
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "Github Actions"
        git checkout -b release/esmorga-${{ inputs.release_num }}
        echo "release/esmorga-${{ inputs.release_num }}" > .github/tmp/branch.txt
        git add .github/tmp/branch.txt
        git commit -m "${{ inputs.usKey }}"
        git push -u origin "release/esmorga-${{ inputs.release_num }}"
