name: Deploy PROD Env 
run-name: ${{ github.actor }} is deploying release to PROD Env 🚀
on:

  workflow_dispatch:
    inputs:
      environment:
        description: 'Entorno de despliegue (staging, production)'
        required: true
        default: 'staging'

jobs:
  Deploy:
    name: Deploy to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:

      - name: Create .env
        run: |
          echo "NODE_ENV=${{vars.NODE_ENV}}" >> .env

      - name: Deploy to PROD
        uses: ./.github/actions/Deploy
        with:
          SSHRSA: ${{ secrets.SSHRSA}}
          ENV: PROD
