name: Deploy PROD Env
run-name: ${{ github.actor }} is deploying release to PROD Env 🚀
on:

  workflow_dispatch:
    inputs:
      environment:
        description: Entorno de despliegue (staging, production)
        required: true
        default: staging

jobs:
  Deploy:
    name: Deploy to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:

    - name: Create .env
      run: |
        echo MONGODB_URI=${{secrets.MONGODB_URI}} >> .env 
        echo NODE_ENV=${{vars.NODE_ENV}} >> .env 
        echo JWT_SECRET=${{secrets.JWT_SECRET}} >> .env 
        echo ACCESS_TOKEN_TTL=${{vars.ACCESS_TOKEN_TTL}} >> .env 
        echo MAX_PAIR_OF_TOKEN=${{vars.MAX_PAIR_OF_TOKEN}} >> .env 
        echo EMAIL_USER=${{vars.EMAIL_USER}} >> .env 
        echo EMAIL_PASS=${{secrets.EMAIL_PASS}} >> .env 

    - name: Deploy to PROD
      uses: ./.github/actions/Deploy
      with:
        SSHRSA: ${{ secrets.SSHRSA}}
        ENV: PROD
