name: Setup Secrets

on:
  workflow_call:

jobs:
  setup-secrets:
    runs-on: ubuntu-latest
    outputs:
      VARS: ${{ steps.step1.outputs.VARS }}

    steps:
      - name: Configurar variables de entorno a partir de secrets
        run: |
          echo "APP_PORT=${{ vars.APP_PORT }}" >> $GITHUB_ENV
          echo "APP_PORT=${{vars.APP_PORT}}"  >> $GITHUB_ENV
          echo "ACCESS_TOKEN_TTL=${{vars.ACCESS_TOKEN_TTL}}" >> $GITHUB_ENV
          echo "MAX_PAIR_OF_TOKEN=${{vars.MAX_PAIR_OF_TOKEN}}" >> $GITHUB_ENV
          echo "CYPRESS_BASE_URL=http://localhost:${{vars.APP_PORT}}/" >> $GITHUB_ENV
          echo "DNS_NAME=${{vars.DNS_NAME}}" >> $GITHUB_ENV
          echo "EMAIL_USER=${{vars.EMAIL_USER}}" >> $GITHUB_ENV
          echo "APP_LINK=${{vars.APP_LINK}}" >> $GITHUB_ENV
          echo "VARS=$GITHUB_ENV" >> $GITHUB_OUTPUT
      - run: ls
        # DNS_NAME: http://localhost:3000
          # EMAIL_USER: esmorgamailservice@gmail.com
          # APP_LINK: https://www.google.com
    
          # echo "AIO_TOKEN: ${{ secrets.AIO_TOKEN }}" >> $GITHUB_ENV
          # echo "GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
          # echo "POSTMAN_TOKEN: ${{ secrets.postmanToken }}" >> $GITHUB_ENV
    
