name: When Main Changes
run-name: Testing and Deploying new code to QA Env 🚀
on:
  push:
    branches:
    - main

jobs:
  RunUnitTests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: ./.github/actions/runUnitTests
        env:
          NODE_ENV: LOCAL
          APP_ENV: LOCAL
  BuildAndPushDocker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: RunUnitTests
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build and Push Image
        uses: ./.github/actions/pushDockerImage
        with:
          image_name: esmorga-backend/esmorga-backend
          image_tag: ${{ github.sha }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

  DeployToQA:
    needs: BuildAndPushDocker
    uses: ./.github/workflows/Deploy.yml
    secrets: inherit
    with:
      environment: QA
      image_and_tag: ghcr.io/esmorga-backend/esmorga-backend:${{ github.sha }}
